import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import '../styles/globals.css'
import Header from '@/components/common/Header'
import Footer from '@/components/common/Footer'
import { AOSWrapper } from '@/components/common/AOSWrapper'

const inter = Inter({
	subsets: ['latin'],
	variable: '--font-inter',
})

export const metadata: Metadata = {
	title: 'Create Next App',
	description: 'Generated by create next app',
}

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode
}>) {
	return (
		<html lang='uz'>
			<body className={`${inter.variable} antialiased`}>
				<AOSWrapper>
					<Header />
					{children}
					<Footer />
				</AOSWrapper>
			</body>
		</html>
	)
}
